### ISSUE TITLE
Error trying to create Session

### ISSUE THREAD

**Issue by sheldonyon** [Microsoft/WinAppDriver#204] opened 2017-06-13 22:42 UTC
I am trying to create a session using an Http post session with {"desiredCapabilities":{"app":"Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge","deviceName":"WindowsPC","platformName","Windows"}} in the payload

I get a {"status":13, "value":{"error":"unknown error", "message":"An unknown error occurred in the remote end while processing the command."}}

**Comment by yodurr** [comment] 2017-06-14 01:12
Hi @sheldonyon that error is a generic error, difficult to know what the cause is from that - can you provide more details about what test runner and language you're using to run the test?

**Comment by sheldonyon** [comment] 2017-06-14 16:11
I was using just an HTTP request typed in by hand we are trying to not use appium and go directly to WinAppDriver. Are there additional API details for the WinAppDriver commands.

**Comment by timotiusmargo** [comment] 2017-06-14 18:04
We use the following document as a reference when we implement the API endpoints as it is what most Appium client supports:
https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol

It may help to run the following test and copy the session creation request from the log if you are doing manual POST Http Request

**Comment by timotiusmargo** [comment] 2017-08-18 21:54
Below is a sample JSON Wire Protocol payload expected to launch **Microsoft Edge** as you attempted above.

```
POST /session HTTP/1.1
Accept: application/json, image/png
Connection: Keep-Alive
Content-Length: 148
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"desiredCapabilities":{"app":"Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge","platformName":"Windows"}}
HTTP/1.1 200 OK
Content-Length: 196
Content-Type: application/json

{"sessionId":"F734F2E6-1D64-4798-93CE-A346228FFE17","status":0,"value":{"app":"Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge","platformName":"Windows"}}
```

The new [v1.0-RC](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC) release also has some optimization on application launching and more detailed exception. Please give it a try to validate if this is still an issue.

**Comment by hassanuz** [comment] 2018-03-20 20:38
Closing ticket due no further comments.

**Closed by hassanuz** 2018-03-20 20:38 UTC
