### ISSUE TITLE
raise an error when testing an Office app

### ISSUE THREAD

**Issue by ketanaka-MSFT** [Microsoft/WinAppDriver#111] opened 2016-12-15 00:43 UTC
Currently winappdriver can't run x64 app such as Office 365 ProPlus. 
When running a test for it, an error has been raised like below:
Stack Trace: 
場所 OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse) 
場所 OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) 
場所 OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities) 
場所 OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities) 
場所 OpenQA.Selenium.Appium.AppiumDriver`1..ctor(Uri remoteAddress, ICapabilities desiredCapabilities) 
場所 OpenQA.Selenium.Appium.iOS.IOSDriver`1..ctor(Uri remoteAddress, DesiredCapabilities desiredCapabilities) 
場所 UnitTestProject3.UnitTest1.Setup(TestContext context) 
場所 c:\users\ketanaka\documents\visual studio 2015\Projects\UnitTestProject3\UnitTestProject3\UnitTest1.cs:行 27 
結果 のメッセージ: クラス初期化メソッド UnitTestProject3.UnitTest1.Setup は例外をスローしました。System.InvalidOperationException: System.InvalidOperationException: An unknown error occurred in the remote end while processing the command.

**Comment by ianceicys** [comment] 2016-12-15 14:27
@ketanaka-MSFT Can you post a link to a git repo with a code sample that reproduces the issue. This appears to be a duplicate of the issue (https://github.com/Microsoft/WinAppDriver/issues/104) I logged with Microsoft Word 2016 and what appears to be an issue with running elevated applications. 

Why do you believe the issue you are logging is related to x64 vs x86 applications?

**Comment by ketanaka-MSFT** [comment] 2016-12-16 03:48
thanks @ianceicys  it seems little different from your issue, I ran the test without elevated command prompt.
The only thing I change code on WordTest sample is replacing the path text from "C:\Program Files (x86)\Microsoft Office\root\Office16\WINWORD.EXE" to "C:\Program File\Microsoft Office\root\Office16\WINWORD.EXE"
I'll test another machine with x86 Office later, and report the result.

**Comment by ketanaka-MSFT** [comment] 2016-12-16 09:50
After investigating this, I put my test results as below:
x64 version of Office 365 ProPlus (Click to Run) : Failed
x86 version of Office 365 ProPlus (Click to Run) : Failed
x86 version of Office 2016 (MSI) : Failed
x64 version of the other App (I tested PowerBI Desktop) : Success
x64 version of system app (Notepad.exe) : Success
Any idea?

**Comment by yodurr** [comment] 2017-01-21 01:30
What version of WinAppDriver are you using?  What version of Windows 10?

**Comment by ketanaka-MSFT** [comment] 2017-01-21 02:23
My WinAppDriver is 0.7,and Win 10 is 1607.

**Comment by yodurr** [comment] 2017-02-06 23:53
can you try the tests not using uppercase ".EXE" in the application being tested, change path to ".exe" and see what the error is now, or if possibly this is now working for you.

There's a bug in launching an app where we don't support uppercase ".EXE" and we'll fix this in the next release of WinAppDriver.

**Comment by ketanaka-MSFT** [comment] 2017-02-07 07:36
wow! it works!
thank you yoddur.
I hope this bug be fixed soon.

**Comment by yodurr** [comment] 2017-02-08 17:53
Great.  Closing this issue.  You can track progress on this bug here:
https://github.com/Microsoft/WinAppDriver/issues/143

**Closed by yodurr** 2017-02-08 17:53 UTC
