### ISSUE TITLE
Winappdriver just launches the app and then throws an exception 

### ISSUE THREAD

**Issue by viji-123** [Microsoft/WinAppDriver#321] opened 2017-12-05 15:02 UTC
Hi Team,

Am using pycharm to run the code (written with Python) using selenium  and winappdriver. Below is the code :-  Its quite simple.

from selenium import webdriver

desired_caps = {}
desired_caps["app"] = "C:\Program Files\AppName.exe"
driver = webdriver.Remote( command_executor='http://127.0.0.1:4723', desired_capabilities=desired_caps)
driver.set_page_load_timeout(20)

This code launches the app and then fails. Below is the trace:

 File "C:/Users/xyz/PycharmProjects/SeleniumProj/SeleniumTest1/Test1.py", line 6, in <module>
    driver = webdriver.Remote( command_executor='http://127.0.0.1:4723', desired_capabilities=desired_caps)
selenium.common.exceptions.WebDriverException: Message: Operation timed out. (Exception from HRESULT: 0x80131505)

**In the winappdriver i see the below exception**

POST /session HTTP/1.1
Accept: application/json
Accept-Encoding: identity
Connection: close
Content-Length: 182
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:4723
User-Agent: Python http auth

{"capabilities": {"firstMatch": [{}], "alwaysMatch": {}}, "desiredCapabilities": {"app": "C:\\Program Files\\AppName.exe"}}
HTTP/1.1 500 Internal Error
Content-Length: 117
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"Operation timed out. (Exception from HRESULT: 0x80131505)"}}

**Comment by viji-123** [comment] 2017-12-07 14:52
Can someone pls help?

**Comment by timotiusmargo** [comment] 2017-12-07 20:11
Hi @viji-123,

Which version of WIndows Application Driver are you using? If you haven't done so would you please try the latest [1.0](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0) release?

**Comment by viji-123** [comment] 2017-12-07 20:13
Am using the latest 1.0 release

**Comment by timotiusmargo** [comment] 2017-12-07 20:26
Can you successfully launch the application you specified under the `app` capability from non-administrative command line or a run window?

**Comment by viji-123** [comment] 2017-12-07 20:30
Yes. from a run window am able to launch the app

**Comment by timotiusmargo** [comment] 2017-12-07 21:12
I see. The error you saw is a result of an exception that we need to dig deeper into. Can you share the application you are trying to launch?

**Comment by viji-123** [comment] 2017-12-08 15:02
Its an internal application for my company. Am afraid I won't be able to share it. Sorry about that.
Is there anyother way ? Can I share you my desktop personally ?

**Comment by hassanuz** [comment] 2017-12-08 23:59
@viji-123,
Is there any way you can share a mini-project that has this launch method? +Can you provide additional details on the app launch, e.g. how long it takes for the .exe to instantiate, what kind of application (UWP/Win32/.netForms, etc)?
Thanks

**Comment by viji-123** [comment] 2017-12-12 15:46
Below is the code 

from appium import webdriver

desired_caps = {}
desired_caps["app"] = "C:\Program Files\AppName.exe"
driver = webdriver.Remote( command_executor='http://127.0.0.1:4723', desired_capabilities=desired_caps)
driver.set_page_load_timeout(20)


It takes 10-15 seconds to open the application. Then it fails. It is a WPF app.

**Comment by viji-123** [comment] 2017-12-18 15:00
Can someone pls help

**Comment by viji-123** [comment] 2017-12-19 15:06
Any update on this issue? Is there any workaround? Pls let me know

**Comment by timotiusmargo** [comment] 2017-12-19 22:25
Hi @viji-123,

I can't really tell what is causing the **operation timed out** exception you encountered with your app without a repro. So far this is the first time of this error we ever heard of. We even tried to simulate a long starting application without encountering the exception you saw. 

However, it sounds like you can create a session by [attaching to currently running application window](https://github.com/Microsoft/WinAppDriver/tree/v1.0#attaching-to-an-existing-app-window) as a workaround since your application launches successfully. The session creation sequence will look like:
1. Create a session with your `app` id like what you did
2. Create a [desktop session](https://github.com/Microsoft/WinAppDriver/tree/v1.0#creating-a-desktop-session) that can be used to locate your application window once it is opened
3. Wait until the application window is opened
4. Locate the application window element using the **desktop session**
5. Create a new session with the `NativeWindowHandle` attribute of the application window element as shown in the snippet on https://github.com/Microsoft/WinAppDriver/tree/v1.0#attaching-to-an-existing-app-window

Let us know if the workaround help your scenario. At the same time, let's work together to identify the root cause of the exception you saw.

**Comment by viji-123** [comment] 2017-12-20 17:16
Hi @timotiusmargo 

Thanks a lot for helping me on this issue. Earlier I worked in VS using C# at that time I faced an issue  , the reason was the splash screen , when i disabled the splash screen it worked.
So i used the same logic here (now am using Pycharm/ Python) it didnt work. When i enabled back the splash screen , its working now. Its quite strange why it worked in one case and not in another.
Anyway its working now.
Thanks a lot for your support. Appreciate your entire team for the efforts !!

**Comment by hassanuz** [comment] 2018-03-20 20:45
Closing ticket due to issue resolution.

**Closed by hassanuz** 2018-03-20 20:45 UTC

**Comment by HariniShiva** [comment] 2018-04-02 19:18
Hi,
How to check checkbox inside in stackpanel?
        <StackPanel Grid.Row="4" Grid.Column="1" Grid.RowSpan="1" Grid.ColumnSpan="2" >
            <ListBox x:Name="lstBox_Tests" Background="White" IsEnabled="False" ItemsSource="{Binding DiagTestList}" HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
                <ListBox.ItemTemplate>
                    <DataTemplate>
                        <CheckBox x:Name="chkBox_Tests" Content="{Binding TheText}" Tag="{Binding TheValue}" Checked="chkBox_Tests_Checked" Unchecked="chkBox_Tests_Unchecked" Height="10" />
                    </DataTemplate>
                </ListBox.ItemTemplate>
            </ListBox>
        </StackPanel>

**Comment by KiranBehara** [comment] 2019-01-31 16:11
Hi,

Am able to launch the application but it is throwing time-out error immediately  & session is returning null value. I tried with time-out parameter but still the same issue.

session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities, TimeSpan.FromMinutes(2));

FYI - The App i am trying to launch is a thick client, it will take 60-90 minutes to load the screen/modules & also we have a splash screen which appears immediately when we launch our application.

Can someone please help me. 

Thank You!

Regards,
Kiran B.
