### ISSUE TITLE
WinAppDriver does not work with WPF/WinForms applications

### ISSUE THREAD

**Issue by QuantumDeveloper** [Microsoft/WinAppDriver#83] opened 2016-10-28 13:10 UTC
`DesiredCapabilities appCapabilities = new DesiredCapabilities();
 appCapabilities.SetCapability("app", @"C:\myWPFApp.exe");
 NotepadSession = new IOSDriver<IOSElement>(new Uri(AppDriverUrl), appCapabilities);`

On the third line it starts my app and just hangs.
But with Native Win32/UWP applications driver creates correctly and quickly.

Is there a way to prevent driver from hanging when starting WPF/WinForm applications?

**Comment by yodurr** [comment] 2016-10-31 17:31
I've reproduced the bug.  Thanks for filing this.  We're investigating.

**Comment by Greeny99** [comment] 2016-11-14 09:06
Is there any update on the WPF/Winforms issue?

**Comment by timotiusmargo** [comment] 2016-11-14 18:59
We have a fix implemented that will be available in the next release

**Comment by ivan-prodanov** [comment] 2016-11-17 15:45
Is there a nightly drop that we can use until you guys get the next release rolling? I'd really like to start adapting this, but the wpf/winforms issue is a huge blocker.

**Comment by rahul24** [comment] 2016-11-17 17:54
When you guys are releasing new build?

**Comment by ianceicys** [comment] 2016-11-18 20:19
Looking forward to the new build? Any ETA on when it will be released?

**Comment by connect2sandeep** [comment] 2016-11-24 04:42
Is there a fix or a workaround for this issue?

**Comment by ianceicys** [comment] 2016-11-26 03:21
I think the workaround is to just waiting for the new release...hopefully we will know more by Wednesday November 30th.

**Comment by ivan-prodanov** [comment] 2016-11-26 08:09
This is not a workaround... I suggest nightly build drops to be provided as well. Yes, it's beta and all but having these beta versions plus nightly builds gives me and my team the benefit to integrate this thing faster within our organization. This might lead to more issues, which is not necessarily a bad thing. Nevertheless, blockers like this issue will be fixed and delivered much faster. Nightly builds => more immediate feedback => less blockers => more users => stronger community => even more feedback => better quality.

**Comment by viji-123** [comment] 2016-11-30 16:12
Please let us know when can we expect the fix for wpf applications (as winappdriver doesnt work for wpf app currently) . 
Today is Nov 30, was expecting the new release today. Please provide us the fix ASAP as this is blocker for us

**Comment by SimonKirkhamCL4U** [comment] 2016-11-30 16:55
I would also like to know when we can expect a fix for this or a workaround so we can start experimenting.

**Comment by yodurr** [comment] 2016-11-30 21:48
Thanks for your patience.  We're trying to get a release out by EOD today.

**Comment by ivan-prodanov** [comment] 2016-12-01 01:21
@yodurr Just saw the release, but it states WPF only. What about WinForms? Is this going to be supported?

**Comment by yodurr** [comment] 2016-12-01 01:46
Yes WinForms support is included.  We'd really appreciate if you can try 0.7 and please file a bug if it isn't working for you.  Thanks!

**Comment by kfrajtak** [comment] 2016-12-01 09:24
Hi @yodurr,
thanks for the release, a session for WinForms application is created (previously it was hanging on that line).
However, now I have a problem with selecting an element. I have a simple WinForms app with a `TextBox` called `textBox1`, but neither `session.FindElementById` nor `session.FindElementByName` methods are not able to find that element:

> System.InvalidOperationException: An element could not be located on the page using the given search parameters.

The PageSource property of the session contains this fragment

```
<Edit AcceleratorKey="" AccessKey="" AutomationId="textBox1"
 ClassName="WindowsForms10.EDIT.app.0.2bf8098_r9_ad1" FrameworkId="WinForm" 
 HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True"
 IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False"
 IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="edit"
 Name="" Orientation="None" ProcessId="13860" RuntimeId="42.331658"
 x="151" y="158" width="100" height="20" />
```

The element can be located using `FindElementByTagName` method.

Thanks for help (maybe I'm missing something basic).

Karel

**Comment by SimonKirkhamCL4U** [comment] 2016-12-01 11:30
Working for me now (sometimes but I think that is due to the app under test).

**Comment by ianceicys** [comment] 2016-12-01 16:23
The WpfNotepad sample now works for me with the latest .7 release.

https://github.com/Microsoft/WinAppDriver/blob/v0.7-beta/Samples/C%23/WPFNotepadTest/WPFNotepadTest/Scenario.cs#L29-L30
 
![image](https://cloud.githubusercontent.com/assets/3976990/20801946/70575ee0-b7b8-11e6-890f-d4be0ed729f9.png)

**Comment by kfrajtak** [comment] 2016-12-01 16:37
@ianceicys Can you post the fragment of the PageSource XML document?

**Comment by viji-123** [comment] 2016-12-01 18:38
Hi..After using the latest release , my wpf app opens up successfully. But am not able to locate any element using id or classname or name. Am i missing something? 
Note: Am using Inspect tool to locate the element.

**Comment by ianceicys** [comment] 2016-12-02 13:52
@kfrajtak Here is the source code for my sample app WPFNotepad.exe

https://github.com/ianceicys/WinAppDriver/blob/0648400f87dce0ed511f851080e68e93f77c1f76/Samples/C%23/WPFNotepadTest/WPFNotepadTest/Scenario.cs#L27-L37

Here is my quick repo of it working. Can you please try out this very simple sample to find out if it works for you? 
https://www.youtube.com/watch?v=xvJ2ALe0mt8

**Comment by kfrajtak** [comment] 2016-12-02 17:08
@ianceicys, it works! It works with a session created by using both `RemoteWebDrive` and `IOSDriver<IOSElement>` classes.

It still does not work for WinForms app ...

What I noticed is that elements in WPF app do have Name and do not have AutomationId (at least in the PageSource XML document):

```
<MenuItem AcceleratorKey="" AccessKey="Alt+F" AutomationId="" ClassName="MenuItem"
 FrameworkId="WPF" HasKeyboardFocus="False" HelpText=""
 IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True"
 IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType=""
 LocalizedControlType="menu item" Name="File" Orientation="None" ProcessId="27144"
 RuntimeId="7.27144.34576242" x="138" y="161" width="33" height="21"
 ExpandCollapseState="Collapsed" IsAvailable="True" />
```

If you are willing to give it a try, there's a project I created at [https://github.com/kfrajtak/UITesting](https://github.com/kfrajtak/UITesting) (you'll have to change the hard-coded paths). 
Thanks,
Karel

**Comment by viji-123** [comment] 2016-12-02 18:40
@kfrajtak .  Am also working in WPF app. Some of the elements have 'AutomationId' & some have 'Name'. But when I use AutomationId or Name , it doesn't locate the element. For some reason it fails with element not found exception. Is there any solution or workaround for this issue?

**Comment by ianceicys** [comment] 2016-12-02 20:39
@viji-123 Can you please try to find the control using FindElementByTagName?

**Comment by viji-123** [comment] 2016-12-02 20:54
@ianceicys 

I tired as you said. 

![tagname](https://cloud.githubusercontent.com/assets/22593499/20850021/4d51fa00-b8a7-11e6-8b76-73828c56ccdc.png)

The field corresponding to LocalizedControlType was "tab item". So I used it as below in my code

Session.FindElementByTagName("tab item").Click();

Still It didnt work.  Am i missing something? Please let me know your thoughts

**Comment by ianceicys** [comment] 2016-12-02 21:09
Can you try 
Session.FindElementByTagName("Tab").Click(); 
![image](https://cloud.githubusercontent.com/assets/3976990/20850546/ba1fd9f2-b8a9-11e6-914c-fe12b7314dbd.png)


@yodurr It would be great to get a listing of what the TagName values are available or how they are determined.

**Comment by viji-123** [comment] 2016-12-02 21:20
Hi @ianceicys 

Am trying to automate the WPF app that we are using in our project. In our application the LocalizedControlType is "tab item". Hence I used Session.FindElementByTagName("tab item").Click();

This didnt work. It isnt able to locate the element

**Comment by ianceicys** [comment] 2016-12-02 21:24
Hmmm... Good point. I really don't have a workable solution then. I'd think one avenue to debug the issue might be to get all the elements that the appdriver detects and see how it it finding it. 

//sudo code (this doesn't compile 👎 )
var elementsfound = session.FindElements();

**Comment by rahul24** [comment] 2016-12-03 06:04
working like a charm .. Just tested on my WPF app. Will post issues, if any. 

Q) In selenium, when click event occur then it wait for next page to load. Can we achieve same functionality with this framework too, without explicitly holding thready by using sleep?

**Comment by rahul24** [comment] 2016-12-03 14:08
One more observation, I was playing with one of my old WPF app where the starting point is set to splash screen. On that screen, am asking the user to log in and once the user is authenticated that screen would unload and open another screen which is basically the main app. I'm trying to automate this scenario but couldn't able to crack - how to start another session with another screen, basically. If I use existing session then getting - "Currently selected window has been closed". Please help me to automate this scenario.

**Comment by khouzam** [comment] 2016-12-05 18:36
Hi @rahul24,

Would you mind opening this as a new issue, that can have its own discussion? That way we can keep the topic of the thread.

Thanks

**Comment by kfrajtak** [comment] 2016-12-06 07:14
Hi @khouzam,
how about the problems with the WinForms application? Can you have a look at it?
Thanks

**Comment by viji-123** [comment] 2016-12-09 17:51
Hi @ianceicys 

I tried using var elementsfound = session.FindElements(); to find out all the elements in the wpf app. But unfortunately it didnt work. Is there a way to find the list of elements in the wpf app which is detected by the driver

**Comment by yodurr** [comment] 2017-02-16 18:50
closing.  please open new issues if anything wasn't addressed.  Thanks.

**Closed by yodurr** 2017-02-16 18:50 UTC
