### ISSUE TITLE
Access to Raw Element

### ISSUE THREAD

**Issue by 3belut** [microsoft/WinAppDriver#959] opened 2019-11-12 14:57 UTC
I have an application where some WPF objects have those properties set to false :
![image](https://user-images.githubusercontent.com/35958350/68682028-c0ef5400-0564-11ea-98a6-3a8d707bc819.png)
Therefore, those elements are visible only in raw view of Inspect.exe. I saw that [some filter can be set](https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-treeoverview#raw-view) to access this elements with UI Automation Library

How can I access them with Win App Driver ?

**Comment by pm90pl** [comment] 2019-11-13 20:26
This issue is a duplicate of #905

**Comment by hassanuz** [comment] 2019-12-02 20:30
Not currently supported. Will investigate into adding this in the future. Closing due to duplicate.

**Closed by hassanuz** 2019-12-02 20:30 UTC
Labels: Enhancement, duplicate
